### ISSUE TITLE
도커의 CMD, ENTRYPOINT와 쿠버네티스의 command, args

### ISSUE THREAD

**Issue by saintbeller96** [saintbeller96/TIL#9]
도커 CMD <-> 쿠버네티스 args
도커 ENTRYPOINT <-> 쿠버네티스 command

```dockerfile
FROM Ubuntu
ENTRYPOINT ["sleep"]
CMD ["5"]
```

```yaml
...
spec:
  containers:
    - name: ubuntu-sleeper
      image: ...
      command: ["sleep"] # Dockerfile의 ENTRYPOINT를 덮어씀
      args: ["10"] # Dockerfile의 CMD를 덮어씀
```
